### ISSUE TITLE
Crashing since start of KnC

### ISSUE THREAD

**Issue by Kravchuck** [ifeherva/HearthDuster#8]
Hello, the app stopped working since the release of the latest expansion, is this expected? 

I hope you manage to fix or update it, because the tool was really helpful :)

**Comment by ifeherva** [comment]
Sure, I just didnt know anyone is using this app :)

**Comment by ifeherva** [comment]
I just release 0.9.2 that has the new expansion, small bugfixes and also CSV export for your collection!

**Comment by Kravchuck** [comment]
Thank you! It's appreciated :)
